### ISSUE TITLE
Почитай вот тут про метод .sort() и какие бывают с ним нюансы https://learn.javascript.ru/array-methods#sort-fn

### ISSUE THREAD

**Issue by DmitriyPavlovskyi** [tartakovskyi/advanced-js#2]
https://github.com/tartakovskyi/advanced-js/blob/489f8300d954d24acfaba02aa60d26b5c9cefb8a/lesson_01/work_2.html#L70

**Comment by tartakovskyi** [comment]
Спасибо. Почитал и добавил функцию сортировки
